# Site settings
baseURL = "https://woodbury-hoa.com/"
copyright = "All rights reserved. 2017-2023"
disqusshortname = ""
languagecode = "en-US"
#paginate = 5
pluralizelisttitles = false
theme = "casper"
title = "Woodbury HOA"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

#[[menu.main]]
#name = "Documents"
#pre = ""
#url = ""
#weight = 100

[params]
author = ""
authorlocation = ""
authorwebsite = ""
bio = ""
cover="/images/current.jpg"
description = "Woodinville, WA"
githubName = ""
googleAnalyticsUserID = "G-RRWJ8EMH8J"
hideHUGOSupport = true
logo = ""
facebookName="groups/101482933516141/"
RSSLinkEnabled = false
contactUs="True"

[permalinks]
post = "/:slug/"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"

[markup.goldmark.renderer]
unsafe = true
